spring:
    cloud:
        gateway:
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "http://localhost:4200"
                        allowedHeaders: '*'
                        allowedMethods:
                            - GET
                            - PUT
                            - POST
                            - DELETE
                            - PATCH